export const icons = {
  down: require("../assets/icons/down.png"),
  // mobileLogin: require("../assets/icons/down.png"),
  // apple: require("../assets/icons/apple.png"),
  // google: require("../assets/icons/google.png"),
  // facebook: require("../assets/icons/facebook.png"),
  // phone: require("../assets/icons/cellphone.png"),
  // ok: require("../assets/icons/ok.png"),
  // logout: require("../assets/icons/logout.png"),
  // english: require("../assets/icons/english.png"),
  // gk: require("../assets/icons/gk.png"),
  // maths: require("../assets/icons/maths.png"),
  // profile: require("../assets/icons/profile.png"),
  // science: require("../assets/icons/science.png"),
  // home: require("../assets/icons/home.png"),
  // favouriteFilled: require("../assets/icons/favouriteFilled.png"),
  // favourite: require("../assets/icons/favourite.png"),
  locationAnimation: require("../assets/locationAnimation.png"),
  brainCalImage: require("../assets/brainCalImage.png"),
  closeRound: require("../assets/closeRound.png"),
  google: require("../assets/google.png"),
  facebook: require("../assets/facebook.png"),
  apple: require("../assets/apple.png"),
  backArrow: require("../assets/backArrow.png"),
};
